End of the update
zwergius/el-danes pull request #65
Opened 2023-04-10 10:28 UTC by Javitocatral

2023-04-10 12:34 UTC, zwergius requested changes

2023-04-10 12:34 UTC, zwergius commented on src/lib/components/Header.svelte
> +      <Anchor id="contact-link" data-sveltekit-preload-data href="/contact">
I am pretty sure that once u have added preload to body you can remove it here

2023-04-10 12:34 UTC, zwergius commented on src/lib/components/ClientsSticker.svelte
> +      data-sveltekit-preload-data
I am pretty sure that once u have added preload to body you can remove it here

2023-04-10 12:56 UTC, Javitocatral commented on src/lib/components/Header.svelte
> +  import { LL } from '../../i18n/i18n-svelte'
If you don't find the module

2023-04-10 13:18 UTC, Javitocatral commented on src/lib/components/FlipButton.svelte
> +  aria-checked={flipped ? true : undefined}
rol button only aria-pressed
aria selected  only this: row, tab, opiton ,gridcell

2023-04-10 13:24 UTC, zwergius commented
Option sounds great!

> On 10 Apr 2023, at 15:18, Javier Gascon Ruiz ***@***.***> wrote:
>
> @Javitocatral commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [src/lib/components/FlipButton.svelte](https://github.com/zwergius/el-danes/pull/65#discussion_r1161713192):
>
>>    tabindex="0"
> -  aria-selected={flipped ? true : undefined}
> +  aria-checked={flipped ? true : undefined}
>
> rol button only aria-pressed
> aria selected only this: row, tab, opiton ,gridcell
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/zwergius/el-danes/pull/65#discussion_r1161713192), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAPXAFH2EYC3ZOKMYS7JTTTXAQCDRANCNFSM6AAAAAAWY2U3UM).
> You are receiving this because you were assigned.Message ID: ***@***.***>

2023-04-10 13:50 UTC, zwergius commented
You should look for a solution to this

> On 10 Apr 2023, at 14:56, Javier Gascon Ruiz ***@***.***> wrote:
>
> @Javitocatral commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [src/lib/components/Header.svelte](https://github.com/zwergius/el-danes/pull/65#discussion_r1161698488):
>
>> @@ -1,5 +1,5 @@
>  <script lang="ts">
> -  import { LL } from '$i18n/i18n-svelte'
> +  import { LL } from '../../i18n/i18n-svelte'
>
> If you don't find the module
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/zwergius/el-danes/pull/65#discussion_r1161698488), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAPXAFCY6L35FZ6CG5RYZNDXAP7QXANCNFSM6AAAAAAWY2U3UM).
> You are receiving this because you were assigned.Message ID: ***@***.***>

2023-04-11 12:34 UTC, zwergius approved these changes
LGTM
![ok usa](https://cloud.githubusercontent.com/assets/2060308/14286270/cab4c110-fb4e-11e5-90ec-2d23a9cb427f.gif)

2023-04-11 12:34 UTC, merged